import type { Product, Category } from "./types"

export const mockCategories: Category[] = [
  {
    _id: "cat-1",
    name: "Electronics",
    slug: { current: "electronics" },
    description: "Latest electronic gadgets and devices",
    image: null,
  },
  {
    _id: "cat-2",
    name: "Clothing",
    slug: { current: "clothing" },
    description: "Fashion and apparel for everyone",
    image: null,
  },
]

export const mockProducts: Product[] = [
  {
    _id: "prod-1",
    name: "Wireless Headphones",
    slug: { current: "wireless-headphones" },
    price: 199.99,
    compareAtPrice: 249.99,
    description: "Premium wireless headphones with noise cancellation and superior sound quality.",
    images: ["/wireless-headphones.png"],
    category: mockCategories[0],
    inventory: 50,
    featured: true,
    tags: ["electronics", "audio", "wireless"],
    _createdAt: "2024-01-15T10:00:00Z",
  },
  {
    _id: "prod-2",
    name: "Smart Watch",
    slug: { current: "smart-watch" },
    price: 299.99,
    compareAtPrice: null,
    description: "Advanced smartwatch with health monitoring and fitness tracking features.",
    images: ["/smartwatch-lifestyle.png"],
    category: mockCategories[0],
    inventory: 25,
    featured: true,
    tags: ["electronics", "wearable", "fitness"],
    _createdAt: "2024-01-14T10:00:00Z",
  },
  {
    _id: "prod-3",
    name: "Designer T-Shirt",
    slug: { current: "designer-t-shirt" },
    price: 49.99,
    compareAtPrice: 69.99,
    description: "Premium cotton t-shirt with modern design and comfortable fit.",
    images: ["/designer-t-shirt.png"],
    category: mockCategories[1],
    inventory: 100,
    featured: false,
    tags: ["clothing", "casual", "cotton"],
    _createdAt: "2024-01-13T10:00:00Z",
  },
  {
    _id: "prod-4",
    name: "Running Shoes",
    slug: { current: "running-shoes" },
    price: 129.99,
    compareAtPrice: 159.99,
    description: "Lightweight running shoes with advanced cushioning and breathable design.",
    images: ["/running-shoes-on-track.png"],
    category: mockCategories[1],
    inventory: 75,
    featured: true,
    tags: ["clothing", "shoes", "sports"],
    _createdAt: "2024-01-12T10:00:00Z",
  },
]
